[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "^1.3"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "^1.4"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "^1.1"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "^1.0"

[[constraint]]
  name = "github.com/jinzhu/gorm/dialects/mysql"
  branch = "master"
